# Generated by Django 3.2.7 on 2021-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localname',
            name='author',
        ),
    ]
