# Generated by Django 3.2.7 on 2021-12-15 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=64)),
                ('country_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.country')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_name', to='Home.fruit')),
            ],
        ),
    ]
