# Generated by Django 3.2.7 on 2021-12-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211212_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='default_flag_image.jpg', upload_to='flag_image'),
        ),
    ]
