# Generated by Django 3.2.7 on 2021-12-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_fruit_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='user',
            new_name='author',
        ),
    ]
