# Generated by Django 3.2.7 on 2021-12-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_localname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalName',
        ),
    ]
