# Generated by Django 3.2.7 on 2021-12-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_fruit_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='default.jpg', upload_to='flag_image')),
            ],
        ),
        migrations.RenameField(
            model_name='fruit',
            old_name='author',
            new_name='user',
        ),
    ]
