# Generated by Django 3.2.7 on 2021-12-12 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_fruit_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='country',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='Home.country'),
        ),
    ]
