# Generated by Django 3.2.9 on 2021-12-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211215_1314'),
        ('Home', '0005_fruit_country'),
    ]

    operations = [
    ]
