# Generated by Django 3.2.7 on 2021-12-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20211211_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.country'),
        ),
    ]
