# Generated by Django 3.2.7 on 2021-12-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_fruit_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
