# Generated by Django 3.2.7 on 2021-12-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_fruit_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='fruit_name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Local_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=64)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.fruit')),
            ],
        ),
    ]
