# Generated by Django 3.2.7 on 2021-12-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20211212_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local_Name',
        ),
    ]
