# Generated by Django 3.2.7 on 2021-12-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20211205_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contribution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
